version: '3'

env:
  GO111MODULE: on

tasks:
  dev:
    desc: "Run the Telegram bot"
    cmds:
      - go run cmd/main.go


  go-build:
    desc: "Build the Go application"
    cmds:
      - go build -o expense-bot main.go

  test:
    desc: "Run all Go tests"
    cmds:
      - go test ./...

  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run

  docker-build:
    desc: "Build Docker image"
    cmds:
      - docker build -t telegram-expense-bot .

  build:
    desc: "Rebuild Docker container service"
    cmds:
      - docker compose down
      - docker compose up --build -d

  clean:
    desc: "Remove built files"
    cmds:
      - rm -f expense-bot export.xlsx
