version: '3'

env:
  GO111MODULE: on

tasks:
  dev:
    desc: "Run the Telegram bot"
    cmds:
      - go run cmd/main.go

  tidy:
    cmds:
      - docker run --rm -v "$PWD":/app -w /app golang:1.21-alpine sh -c "go mod tidy"
    desc: Run `go mod tidy` in clean Go 1.21 container

  build:
    desc: "Build the Go application"
    cmds:
      - go build -o expense-bot main.go

  test:
    desc: "Run all Go tests"
    cmds:
      - go test ./...

  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run

  docker-build:
    desc: "Build Docker image"
    cmds:
      - docker build -t telegram-expense-bot .

  docker-run:
    desc: "Run Docker container"
    cmds:
      - docker run --rm -p 8080:8080 telegram-expense-bot

  clean:
    desc: "Remove built files"
    cmds:
      - rm -f expense-bot export.xlsx
